# This is a basic workflow to help you get started with Actions

name: CI Node

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on

    strategy:
      matrix:
        node-version: [ 16.18.0 ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Runs Build
      - name: Run Build
        run: |
          npm install
          npm run build --if-present

      - name: Release (Package and publish)
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: trebor006
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: trebor006/denuncitybackend:latest

      - name: Pull image from Docker Hub
        run: docker pull trebor006/denuncitybackend:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Tag image
        run:
          docker tag trebor006/denuncitybackend:latest registry.digitalocean.com/denuncity-registry/denuncitybackend:1.0.0
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/denuncity-registry/denuncitybackend:1.0.0

